[13atm01-grub-theme-collection]
src.github = "13atm01/GRUB-Theme"
fetch.github = "13atm01/GRUB-Theme"

[beatoraja]
fetch.url = "https://www.mocha-repository.info/download/beatoraja$ver-modernchic.zip"

[fcitx5-pinyin-zhwiki]
src.archpkg = "fcitx5-pinyin-zhwiki"
src.prefix = "0.2.4."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict"

[feeluown]
src.pypi = "feeluown"
fetch.pypi = "feeluown"
