[13atm01-grub-theme-collection]
src.git = "https://github.com/13atm01/GRUB-Theme.git"
src.branch = "master"
fetch.git = "https://github.com/13atm01/GRUB-Theme.git"

[beatoraja]
src.webpage = "https://www.mocha-repository.info/download.php"
src.regex = "beatoraja(.*)-modernchic.zip"
fetch.url = "https://www.mocha-repository.info/download/beatoraja$ver-modernchic.zip"

[free-download-manager]
src.webpage = "https://debrepo.freedownloadmanager.org/pool/main/f/freedownloadmanager"
src.regex = "freedownloadmanager_(.*)_amd64.deb"
fetch.url = "https://debrepo.freedownloadmanager.org/pool/main/f/freedownloadmanager/freedownloadmanager_$ver_amd64.deb"

[suisei-grub-theme]
src.git = "https://github.com/kirakiraAZK/suiGRUB.git"
src.branch = "main"
fetch.git = "https://github.com/kirakiraAZK/suiGRUB.git"
