[13atm01-grub-theme-collection]
src.github = "13atm01/GRUB-Theme"
fetch.github = "13atm01/GRUB-Theme"

[beatoraja]
src.webpage = "https://www.mocha-repository.info/download.php"
src.regex = "beatoraja(.*)-modernchic.zip"
fetch.url = "https://www.mocha-repository.info/download/beatoraja$ver-modernchic.zip"

[free-download-manager]
src.webpage = "http://debrepo.freedownloadmanager.org/pool/main/f/freedownloadmanager"
src.regex = "freedownloadmanager_(.*)_amd64.deb"
fetch.url = "http://debrepo.freedownloadmanager.org/pool/main/f/freedownloadmanager/freedownloadmanager_$ver_amd64.deb"

[suisei-grub-theme]
src.github = "kirakiraAZK/suiGRUB"
fetch.github = "kirakiraAZK/suiGRUB"
