[13atm01-grub-theme-collection]
src.git = "https://github.com/13atm01/GRUB-Theme.git"
src.branch = "master"
fetch.git = "https://github.com/13atm01/GRUB-Theme.git"

[beatoraja]
src.webpage = "https://www.mocha-repository.info/download.php"
src.regex = "beatoraja(.*)-modernchic.zip"
fetch.url = "https://www.mocha-repository.info/download/beatoraja$ver-modernchic.zip"

[free-download-manager]
src.webpage = "https://debrepo.freedownloadmanager.org/pool/main/f/freedownloadmanager"
src.regex = "freedownloadmanager_(.*)_amd64.deb"
fetch.url = "https://debrepo.freedownloadmanager.org/pool/main/f/freedownloadmanager/freedownloadmanager_$ver_amd64.deb"

[lampghost]
src.github = "Catizard/lampghost"
fetch.github = "Catizard/lampghost"

[star-rail-grub-themes]
# 源信息
src.github = "voidlhf/StarRailGrubThemes"

[star-rail-grub-themes.fetch.github]
# 获取最新 Release 中的 tar.gz 文件（排除源码包）
asset_regex = "^(?!.*(source|src)).*.tar.gz"
owner = "voidlhf"
repo = "StarRailGrubThemes"
type = "release"
multiple_assets = true

[suisei-grub-theme]
src.git = "https://github.com/kirakiraAZK/suiGRUB.git"
src.branch = "main"
fetch.git = "https://github.com/kirakiraAZK/suiGRUB.git"
