# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  acpi-ec = {
    pname = "acpi-ec";
    version = "v1.0.4";
    src = fetchFromGitHub {
      owner = "musikid";
      repo = "acpi_ec";
      rev = "v1.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-gDcEzZKtHMULtTtJSDTRH1W9otSB6IC0E6EBF9j6F7Q=";
    };
  };
  adspower = {
    pname = "adspower";
    version = "7.3.26";
    src = fetchurl {
      url = "https://version.adspower.net/software/linux-x64-global/AdsPower-Global-7.3.26-x64.deb";
      sha256 = "sha256-odERZUvdne2dGlPgeVo7vX1oOHeDfcmAdhsK95uTqHA=";
    };
  };
}
