# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  feeluown = {
    pname = "feeluown";
    version = "4.1.12";
    src = fetchurl {
      url = "https://pypi.org/packages/source/f/feeluown/feeluown-4.1.12.tar.gz";
      sha256 = "sha256-r2Uy2gmPMbPKxRhikovWKTndLsRvixFHyOlxtUFLl44=";
    };
  };
}
