name: Dependabot Auto Merge

on:
  pull_request_target:

jobs:
  auto-merge:
    name: Dependabot Auto Merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'github-actions[bot]' || github.actor == 'github-actions-preview[bot]'

    steps:
      - uses: actions/checkout@v4

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
